# Generated by Django 5.1.1 on 2024-12-26 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='specialization',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='doctor',
            name='birthday',
            field=models.DateField(default='1980-01-01', verbose_name='Birthday'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='degree',
            field=models.CharField(default='General Practitioner', max_length=255, verbose_name='Degree'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='email',
            field=models.EmailField(default='unknown@doctor.com', max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='name',
            field=models.CharField(default='Unknown Doctor', max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='phone',
            field=models.CharField(default='+38099 99 99 999', max_length=15, verbose_name='Phone'),
        ),
    ]
