# Generated by Django 5.1.1 on 2025-01-03 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_doctor_image_alter_doctor_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='experience_years',
            field=models.IntegerField(default=0, verbose_name='Years of Experience'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='hours_support',
            field=models.IntegerField(default=0, verbose_name='Hours of Support'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='patients',
            field=models.IntegerField(default=0, verbose_name='Number of Patients'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='projects',
            field=models.IntegerField(default=0, verbose_name='Number of Projects'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='skills',
            field=models.JSONField(default=dict, help_text="Example: {'Ophthalmologist': '100%', 'ENT Specialist': '90%'}", verbose_name='Skills'),
        ),
    ]
