# Generated by Django 5.1.1 on 2025-01-07 12:44

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_doctor_experience_years_doctor_hours_support_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='default_image.jpg', force_format=None, keep_meta=True, quality=-1, scale=None, size=[1600, 800], upload_to='uploads/medicine/'),
        ),
    ]
