# Generated by Django 5.1.1 on 2024-09-11 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diseases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diseases',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='uploads/medicine/'),
        ),
        migrations.AddField(
            model_name='diseases',
            name='title',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='diseases',
            name='description',
            field=models.CharField(default='', max_length=60),
        ),
    ]
