# Generated by Django 5.1.1 on 2024-09-11 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diseases', '0002_diseases_image_diseases_title_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Diseases',
            new_name='Disease',
        ),
    ]
