# Generated by Django 5.1.1 on 2024-09-11 19:25

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diseases', '0003_rename_diseases_disease'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='default_image.jpg', force_format=None, keep_meta=True, quality=-1, scale=None, size=[1400, 1000], upload_to='uploads/medicine/'),
        ),
    ]
