# Generated by Django 5.1.1 on 2024-09-29 08:42

import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diseases', '0004_alter_disease_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='summary',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='disease',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='default_image.jpg', force_format=None, keep_meta=True, quality=-1, scale=None, size=[400, 200], upload_to='uploads/medicine/'),
        ),
    ]
