# Generated by Django 5.1.1 on 2025-01-07 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diseases', '0005_disease_summary_alter_disease_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disease',
            name='summary',
        ),
        migrations.RemoveField(
            model_name='disease',
            name='title',
        ),
        migrations.AddField(
            model_name='disease',
            name='symptoms',
            field=models.JSONField(default=dict, help_text="Example: {'Fever': 'Common', 'Cough': 'Rare'}", verbose_name='Symptoms'),
        ),
        migrations.AddField(
            model_name='disease',
            name='treatments',
            field=models.TextField(default='Treatment methods or suggestions.', verbose_name='Treatments'),
        ),
        migrations.AlterField(
            model_name='disease',
            name='description',
            field=models.TextField(default='Detailed description about the disease.', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='disease',
            name='image',
            field=models.ImageField(default='default_image.jpg', upload_to='uploads/diseases/'),
        ),
        migrations.AlterField(
            model_name='disease',
            name='name',
            field=models.CharField(default='Unknown Disease', max_length=255, verbose_name='Disease Name'),
        ),
    ]
